services:
  db:
    image: mysql:8.4
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: moodle

  moodle:
    image: moodlehq/moodle-php-apache:8.3
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./moodle-app:/var/www/html
      - moodledata:/var/www/moodledata
    environment:
      MOODLE_DBTYPE: mysqli
      MOODLE_DBHOST: db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: root
      MOODLE_DBPASS: secret
    hostname: host.docker.internal

  app:
    build:
      context: ./socialimpact-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./socialimpact-app:/app
      - ./socialimpact-app/node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  db_data: null
  moodledata: null
