services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: moodle
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  moodle:
    image: moodlehq/moodle-php-apache:8.3
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MOODLE_DBTYPE: mysqli
      MOODLE_DBHOST: db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: root
      MOODLE_DBPASS: secret
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
volumes:
  db_data:
  moodledata:
